### ISSUE TITLE
FR: there is no status indicator for the pad attached.

### ISSUE THREAD

**Issue by matrover** [Predjee/com.irobot.roomba980#3]
if possible, the app shows the pad so the info is somewhere

**Comment by Predjee** [comment]
Can you try out the new just released SDK 3 (Homey v5 supported) version. If you don't have Homey v5 then this won't work since I completely refactored for the new SDK aswell. 

The version is available on https://homey.app/nl-nl/app/com.irobot.roomba980/iRobot/test/

**Comment by matrover** [comment]
Hi, no i've not updated yet. but when i do i'll let you know.

**Comment by CyberSponk** [comment]
See a new "Icon" called "Detected Pad" on Braava M6. Detecting if a Pad is attached or not works.

**Comment by matrover** [comment]
Works for me 4.0.2 ! :) thanks
